### ISSUE TITLE
Check if the file exists

### ISSUE THREAD

**Issue by Rudyweb** [intel777/Wallhaven-Downloader-V2#1]
Could you add an option to check if the file exists before downloading it?

This would avoid wasting server bandwidth if you already have the wallpaper.

Thanks

**Comment by intel777** [comment]
That totally makes sense, will add to TODO list, thanks.

**Comment by intel777** [comment]
Oh, it's actually already implemented. 

Wallhaven Downloader V2/Main.cs 
Line 62:
`if (!File.Exists(save_path + '\\' + image.filename))`
