### ISSUE TITLE
Downloading a collection is not working

### ISSUE THREAD

**Issue by icemtel** [intel777/Wallhaven-Downloader-V2#2]
Thanks a lot for the app! I really appreciate having this tool.

I want to report an issue with downloading a collection -> the process gets stuck at "[Stage 1/2: URL fetching]"

Details:
- The problem occurs with a NON-DEFAULT collection from my own user, works fine with the  "Default" collection.
- I have tried to change visibility to public, but it did not help.
- the app knows my API key

Also, clicking "cancel" is not working: "[Cancel] Signal send, please wait for main and workers threads to respond..." -> but nothing happens afterwards.

**Comment by intel777** [comment]
Thanks for your bug report, it is much appreciated. Fixes will be included in next release (which I plan to do really soon).
