### ISSUE TITLE
readme refinement request

### ISSUE THREAD

**Issue by mingyEx** [intel777/Wallhaven-Downloader-V2#5]
Hello, I think this project should contain the most basic instructions, such as where the downloaded file will be placed, what each part of the interface does, what format should be entered in each input box, and what is the expected effect after the button is pressed.

I really don't know what to enter in `Search can be empty` and I don't know what the expected effect is, I clicked on download and I don't know where the file will be placed.
You shouldn't expect every user to be familiar with WinForms development and then figure this out from the source code.

**Comment by mingyEx** [comment]
Now I know that I need to enter the name instead of the link or id in the search box, and I will try other features by myself.
By the way, does the author have any plans to support multiple language versions?

**Comment by CyberEnemy** [comment]
@KargathEx The Search (can be empty) box indicates that you can search any and all tags on wallhaven.cc. You can also input the id of the tag, ie. id:2278 for the "#minimalism" tag. 
It is not related to where you save the file to, it's only related to what you want to download.
The button "Save to..." under "Controls" on the other hand, IS related to where you want to save the selection of wallpapers to.
